steps:
  # Dockerイメージのビルド
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/product-support-api'
      - '--build-arg'
      - 'GOOGLE_CLOUD_PROJECT=$PROJECT_ID'
      - '--build-arg'
      - 'GOOGLE_CLOUD_LOCATION=${_REGION}'
      - '.'
    id: 'build'
  
  # イメージのContainer Registryへのプッシュ
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/product-support-api'
    id: 'push'
    waitFor: ['build']
  
  # Cloud Runへのデプロイ（ビルドのみモードでない場合）
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - '${_SERVICE_NAME}'
      - '--image'
      - 'gcr.io/$PROJECT_ID/product-support-api'
      - '--platform'
      - 'managed'
      - '--region'
      - '${_REGION}'
      - '${_AUTH_FLAG}'
      - '--set-env-vars'
      - 'GOOGLE_CLOUD_PROJECT=$PROJECT_ID,GOOGLE_CLOUD_LOCATION=${_REGION}'
    id: 'deploy'
    waitFor: ['push']
    allowFailure: true

images:
  - 'gcr.io/$PROJECT_ID/product-support-api'

substitutions:
  _REGION: asia-northeast1
  _SERVICE_NAME: product-support-api
  _AUTH_FLAG: --allow-unauthenticated
  _BUILD_ONLY: false 